"""
tests/test_predictor.py

Unit tests for end-to-end MiniMedPredictor pipeline.
Uses the demo model weights (generated by scripts/generate_demo_model.py).
"""

import sys
import os
import tempfile
from pathlib import Path

import numpy as np  # type: ignore
import pytest  # type: ignore
import torch  # type: ignore
from PIL import Image  # type: ignore

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from architectures.mini_med_net import MiniMedNet  # type: ignore
from inference.predictor import MiniMedPredictor, DiagnosticResult, _confidence_label  # type: ignore


# ── Fixture: temp model weights ───────────────────────────────────────────────

@pytest.fixture(scope="module")
def demo_weights_path(tmp_path_factory) -> Path:
    """Create random model weights in a temp dir for testing."""
    tmp = tmp_path_factory.mktemp("weights")
    weights_file = tmp / "test_model.pth"
    model = MiniMedNet()
    torch.save({"model_state_dict": model.state_dict()}, weights_file)
    return weights_file


@pytest.fixture(scope="module")
def sample_xray_path(tmp_path_factory) -> Path:
    """Create a random synthetic X-ray image for testing."""
    tmp = tmp_path_factory.mktemp("images")
    img_path = tmp / "test_xray.jpg"
    # Simulate a grayscale X-ray in RGB
    arr = np.random.randint(50, 200, (224, 224, 3), dtype=np.uint8)
    Image.fromarray(arr).save(img_path, "JPEG")
    return img_path


@pytest.fixture(scope="module")
def predictor(demo_weights_path) -> MiniMedPredictor:
    return MiniMedPredictor(
        weights_path=demo_weights_path,
        device="cpu",
        threshold=0.5,
        heatmap_alpha=0.4,
    )


# ── Tests ──────────────────────────────────────────────────────────────────────

class TestPredictor:
    """Integration tests for MiniMedPredictor."""

    def test_predict_returns_diagnostic_result(self, predictor, sample_xray_path):
        result = predictor.predict(sample_xray_path)
        assert isinstance(result, DiagnosticResult)

    def test_label_is_valid(self, predictor, sample_xray_path):
        result = predictor.predict(sample_xray_path)
        assert result.label in ("Pneumonia", "Normal"), \
            f"Unexpected label: {result.label}"

    def test_probability_in_range(self, predictor, sample_xray_path):
        result = predictor.predict(sample_xray_path)
        assert 0.0 <= result.probability <= 1.0, \
            f"Probability out of range: {result.probability}"

    def test_confidence_valid(self, predictor, sample_xray_path):
        result = predictor.predict(sample_xray_path)
        assert result.confidence in ("High", "Moderate", "Low"), \
            f"Unexpected confidence: {result.confidence}"

    def test_heatmap_shape(self, predictor, sample_xray_path):
        result = predictor.predict(sample_xray_path)
        assert result.heatmap.ndim == 2, "Heatmap must be 2D (H, W)"
        assert result.heatmap.dtype == np.float32

    def test_overlay_shape(self, predictor, sample_xray_path):
        result = predictor.predict(sample_xray_path)
        assert result.overlay_bgr.ndim == 3, "Overlay must be 3D (H, W, C)"
        assert result.overlay_bgr.shape[2] == 3, "Overlay must have 3 channels (BGR)"

    def test_original_bgr_shape(self, predictor, sample_xray_path):
        result = predictor.predict(sample_xray_path)
        assert result.original_bgr.ndim == 3

    def test_is_pneumonia_flag(self, predictor, sample_xray_path):
        result = predictor.predict(sample_xray_path)
        assert result.is_pneumonia == (result.label == "Pneumonia")

    def test_probability_pct_format(self, predictor, sample_xray_path):
        result = predictor.predict(sample_xray_path)
        pct = result.probability_pct
        assert pct.endswith("%"), f"probability_pct should end with '%': {pct}"

    def test_predict_from_pil(self, predictor):
        pil_img = Image.fromarray(
            np.random.randint(0, 200, (256, 256, 3), dtype=np.uint8)
        )
        result = predictor.predict_from_pil(pil_img)
        assert isinstance(result, DiagnosticResult)

    def test_file_not_found(self, predictor):
        with pytest.raises(FileNotFoundError):
            predictor.predict("nonexistent_file.jpg")


class TestConfidenceLabel:
    """Tests for the _confidence_label helper."""

    def test_high_confidence(self):
        assert _confidence_label(0.95) == "High"
        assert _confidence_label(0.05) == "High"

    def test_moderate_confidence(self):
        assert _confidence_label(0.75) == "Moderate"
        assert _confidence_label(0.25) == "Moderate"

    def test_low_confidence(self):
        assert _confidence_label(0.52) == "Low"
        assert _confidence_label(0.48) == "Low"
